### ISSUE TITLE
Unable to run whisperjav on M1 Mac CTranslate2 CUDA support error

### ISSUE THREAD

**Issue by ShaTinMe** [meizhong986/WhisperJAV#100]
Hi there, I’m seeing the following error when running whisperjav:

`whisperjav - ERROR - Failed to load Faster-Whisper model: This CTranslate2 package was not compiled with CUDA support`

I’m using an M1 MacBook and installed the project by cloning the repository and following the setup instructions. Since macOS does not support CUDA, I’m not sure whether this is a configuration issue or an expected limitation.

Could you please advise on how to run whisperjav correctly on Apple Silicon?

Many thanks.

**Comment by meizhong986** [comment]
The issue is fixed in the update of 1.7.5 hotfox.
Please do an update to the latest commit.
In your env either do:

Option 1: via entry point
whisperjav-upgrade

Option 2: Direct pip install
pip install -U --no-deps git+https://github.com/meizhong986/whisperjav.git


Please let me know if any issues after the fix : Fixes  Issues https://github.com/meizhong986/WhisperJAV/issues/100 and https://github.com/meizhong986/WhisperJAV/issues/107.

**Comment by meizhong986** [comment]
Closing as duplicate of #110 (same root cause: CTranslate2 CUDA error on Apple Silicon). The fix — MPS→CPU fallback with compute_type="auto" — was shipped and confirmed working on M2 Pro. If you're still experiencing issues, please reopen.
