### ISSUE TITLE
Cannot run in CPU mode

### ISSUE THREAD

**Issue by turtlelinguist** [meizhong986/WhisperJAV#107]
I don't have an NVDIA GPU so I tried to run with CPU only. I keep having RuntimeError. 

RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version
[ERROR] Process exited with code 1.
✗ Process Failed: Process exited with code 1. Check console for details.

I installed CPU-only PyTorch but the faster-whisper/ctranslate2 library still tries to initialize CUDA even on CPU builds.
Is there a way to fix this? Thanks

**Comment by meizhong986** [comment]
Are you on a Mac by any chance? 
Are you able to run the transformers or fidelity pipelines?

**Comment by turtlelinguist** [comment]
Thanks! I tried fidelity pipelines after reading your reply and it worked.

**Comment by meizhong986** [comment]
The balanced pipeline should now work as well after the release 1.7.5.

**Comment by meizhong986** [comment]
I assume you're on Mac. 

I just pushed a hotfix (**commit d255cb1**). 
This includes two fixes that should solve the issue:
  - It sets the compute type to "auto" for ctranslate2 models;
  - It adds CLI arguments for --device and --compute-type;

Please do an update to the latest commit. 
In your env  either do: 

**Option 1**: via entry point
  whisperjav-upgrade


**Option 2**: Direct pip install
  pip install -U --no-deps  git+https://github.com/meizhong986/whisperjav.git

**Comment by meizhong986** [comment]
This should be fixed by the same hotfix as #110 — compute_type="auto" and proper device fallback. turtlelinguist confirmed fidelity mode works. If balanced/fast modes still give trouble on v1.8.3, please reopen and I'll dig in.
